TrajectoryPlannerROS:
  max_vel_x: 1.5
  min_vel_x: 0.1
  max_vel_theta: 3.
  min_vel_theta: -3.
  min_in_place_vel_theta: 1.

  acc_lim_theta: 3.
  acc_lim_x: 0.5
  acc_lim_y: 0.
  holonomic_robot: false

#base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 10.0      # 20.0
controller_patience:  150.0      # 15.0

TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /skid4wd/odom
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
    
 # Robot
         
 max_vel_x: 1.5
 max_vel_x_backwards: 0.13
 max_vel_theta: 1.
 acc_lim_x: 1.
 acc_lim_theta: 1.
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "point"
   radius: 0.4 # for type "circular"
   #line_start: [-0.4, 0.0] # for type "line"
   #line_end: [0.4, 0.0] # for type "line"
   #front_offset: 0.2 # for type "two_circles"
   #front_radius: 0.2 # for type "two_circles"
   #rear_offset: 0.2 # for type "two_circles"
   #rear_radius: 0.2 # for type "two_circles"
   #vertices: [ [0.5, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance
    
 xy_goal_tolerance: 0.4
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.4
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 1
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 3
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 3
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 0.5
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

#eband parameters

DWAPlannerROS:
    controller_frequency: 40.0
 # Robot Configuration Parameters
    max_vel_trans: 1.5.
    min_vel_trans: 0.1

    max_vel_x: 1.5.
    min_vel_x: 0.1

    max_vel_theta: 0.5
    min_vel_theta: -0.5

    acc_lim_x: 0.3
    acc_lim_theta: 0.5
    acc_lim_trans: 0.3

    # Differential-drive robot configuration
    holonomic_robot: false
    acc_lim_y: 0.0
    min_vel_y: 0.0
    max_vel_y: 0.0
    vy_samples: 0

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.5
    xy_goal_tolerance: 0.5
    latch_xy_goal_tolerance: true

    # Minimum velocity for the robot to be considered not stop
    trans_stopped_vel: 0.1
    theta_stopped_vel: 0.1

    # Forward Simulation Parameters
    sim_time: 2.0
    vx_samples: 10
    vy_samples: 0
    vth_samples: 20
    penalize_negative_x: true #no longer used

    #sim specific
    sim_granularity: 0.1
    forward_point_distance: 3.
    
    # Trajectory Scoring Parameters
    path_distance_bias: 32.
    goal_distance_bias: 24.
    occdist_scale: 0.020
    stop_time_buffer: 0.5
    
    max_scaling_factor: 0.2       # 0.2

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 2.

    # Global Plan Parameters
    prune_plan: true
