controller_list:
  - name: fake_arm_body_controller
    type: $(arg execution_type)
    joints:
      - shoulder_yaw_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_arm_gripper_controller
    type: $(arg execution_type)
    joints:
      - gripper_revolute_joint
      - gripper_right_joint
initial:  # Define initial robot poses.
  - group: arm_body
    pose: zero_position