controller_list:
  - name: fake_asdas_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
#  - group: asdas
#    pose: home

  []