controller_list:
  - name: fake_arm_controller_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
  - group: arm_controller
    pose: zero_position